<a href="https://colab.research.google.com/github/EngComp-Henrique/Numerical-methods/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_array = np.zeros(shape=10)
null_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
from sys import getsizeof
arr = np.array(list(range(20)))
print(f"Total bytes consumed by the elements of the array: {arr} = {arr.nbytes} bytes")

Total bytes consumed by the elements of the array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] = 160 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(shape=10)
arr[5] = 1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.array(range(10, 50))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
rev = np.flip(arr)
rev

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.array(range(0, 9)).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
result = np.where(arr > 0)
result

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3, dtype='int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.rand(3, 3, 3)

array([[[0.94341521, 0.60969366, 0.37756459],
        [0.27058592, 0.17549297, 0.79492822],
        [0.3027981 , 0.11754485, 0.65379053]],

       [[0.3147891 , 0.61142522, 0.82616673],
        [0.65452685, 0.04325473, 0.95012363],
        [0.39397979, 0.46423463, 0.44185789]],

       [[0.81906888, 0.50545576, 0.16729988],
        [0.74740847, 0.94282649, 0.2457797 ],
        [0.05986146, 0.43402297, 0.78283225]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
min_max_arr = np.random.rand(10, 10)
min_max_arr

array([[0.66005028, 0.90637382, 0.10483403, 0.66435826, 0.61253734,
        0.79150764, 0.21168273, 0.48562472, 0.52098891, 0.98700607],
       [0.38643864, 0.69444089, 0.27140661, 0.30619271, 0.38457857,
        0.11455897, 0.85763366, 0.68715218, 0.9814187 , 0.94591796],
       [0.24812226, 0.89962942, 0.10398858, 0.15602139, 0.68353142,
        0.36845485, 0.0610515 , 0.01208592, 0.57849031, 0.65096261],
       [0.23669266, 0.47441268, 0.75254877, 0.4518056 , 0.49893171,
        0.38861626, 0.75272595, 0.73873535, 0.320574  , 0.66763623],
       [0.40225935, 0.62535656, 0.51234224, 0.87446787, 0.78296244,
        0.54165126, 0.52382114, 0.13461971, 0.53532466, 0.73500257],
       [0.49660128, 0.04264043, 0.91945489, 0.91915418, 0.41387925,
        0.57933567, 0.56921235, 0.95300664, 0.11091974, 0.385062  ],
       [0.35167551, 0.12474813, 0.63901697, 0.00238383, 0.38177515,
        0.17584885, 0.91021129, 0.26981505, 0.85077996, 0.6382707 ],
       [0.60068298, 0.99095185, 0.6594856

In [ ]:
print(f'Menor valor = {np.min(min_max_arr)}\nMaior valor = {np.max(min_max_arr)}')

Menor valor = 0.0023838288594282275
Maior valor = 0.9909518502668566


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
rand_vector = np.random.rand(30)
rand_vector

array([0.08734869, 0.81698874, 0.19128753, 0.91494173, 0.37901995,
       0.44162394, 0.48641615, 0.31198241, 0.09320946, 0.28750534,
       0.03511982, 0.45658698, 0.04008793, 0.28614152, 0.84691324,
       0.57524837, 0.61717479, 0.62045587, 0.67279261, 0.02105105,
       0.15131608, 0.47629646, 0.33959228, 0.03319421, 0.52296014,
       0.15581446, 0.4659322 , 0.97419122, 0.84817555, 0.80876852])

In [ ]:
np.mean(rand_vector)

0.4319379086586296

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr = np.zeros((4, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr[0, :] = np.ones(4)
arr[:, 0] = np.ones(4)
arr[-1, :] = np.ones(4)
arr[:, -1] = np.ones(4)

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
rand_arr = np.random.rand(3, 3)
add_column = np.zeros(3)
add_row = np.zeros(5)
result = np.column_stack((rand_arr, add_column))
result = np.column_stack((add_column, result))
result = np.vstack((add_row, result))
result = np.vstack((result, add_row))
result

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.40931768, 0.7801307 , 0.04815043, 0.        ],
       [0.        , 0.60127162, 0.87527329, 0.71988875, 0.        ],
       [0.        , 0.8729064 , 0.98385091, 0.86031005, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.arange(1, 5)
np.diag(matrix, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
np.tile(np.identity(2), (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile(np.identity(2), (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

### **Question: What is matrix normalization?**

**Answer**: To normalize a matrix means to scale the values such that that the range of the row or column values is between 0 and 1. 

### First approach

We'll modify the elements of the matrix by making mathematical operations.
1. Subtract every element from the mean of the matrix
2. Divide every element by the standart deviation

### Second approach

To help us to normalize matrixes, we'll use the `sklearn.preprocessing.normalize()` method. This method allows us to choose if we want to normalize by columns or by rows


**Read the docs here:**

**1. [sklearn normalize](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html)**

**2. [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)**

**3. [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html)**

In [ ]:
# Importing library
from sklearn.preprocessing import normalize

In [ ]:
# Creating matrix
matrix = np.random.random((5, 5))
matrix

array([[0.9018336 , 0.00821326, 0.18574818, 0.66034303, 0.67426467],
       [0.80364969, 0.23753629, 0.26202607, 0.23526838, 0.1092502 ],
       [0.59930368, 0.81784393, 0.39508837, 0.54084342, 0.61582788],
       [0.98841322, 0.60661474, 0.8376233 , 0.57380267, 0.88577023],
       [0.13206471, 0.09205351, 0.41770218, 0.25236169, 0.26422222]])

In [ ]:
# Normalizing matrix
matrix = (matrix - np.mean(matrix)) / (np.std(matrix))

In [ ]:
matrix

array([[ 1.45141363, -1.65203087, -1.03547175,  0.61274361,  0.66109193],
       [ 1.11043179, -0.85561739, -0.7705671 , -0.86349358, -1.30114075],
       [ 0.40076069,  1.15972681, -0.30845646,  0.19773471,  0.45814744],
       [ 1.75209504,  0.4261512 ,  1.22841837,  0.31219854,  1.39562733],
       [-1.2219085 , -1.36086297, -0.22992119, -0.80413042, -0.7629401 ]])

In [ ]:
# Using `normalize` method
matrix = np.random.rand(25).reshape(5, 5)
matrix

array([[0.32925989, 0.20399743, 0.49053821, 0.01391696, 0.74424818],
       [0.05448694, 0.82400552, 0.83253738, 0.77315544, 0.90867856],
       [0.73066438, 0.32259027, 0.18845461, 0.77391893, 0.50339294],
       [0.64134607, 0.95529083, 0.24345446, 0.66559637, 0.08948587],
       [0.86300945, 0.95522333, 0.6860554 , 0.62177583, 0.54525797]])

In [ ]:
x_normed = normalize(matrix, axis=1, norm='l2')
x_normed

array([[0.33875016, 0.20987726, 0.50467701, 0.01431808, 0.76569967],
       [0.03257068, 0.49256606, 0.49766615, 0.46216939, 0.54318109],
       [0.59151862, 0.26115705, 0.15256582, 0.62653588, 0.40752814],
       [0.47355333, 0.70536201, 0.17976047, 0.49145913, 0.06607405],
       [0.5146616 , 0.56965398, 0.40913384, 0.37080028, 0.32516833]])

In [ ]:
x_normed = normalize(matrix, axis=0, norm='l2')
x_normed

array([[0.24532307, 0.1253218 , 0.40062916, 0.00977613, 0.5345705 ],
       [0.04059682, 0.50621154, 0.67994448, 0.54311215, 0.65267577],
       [0.54439924, 0.19817697, 0.15391342, 0.54364847, 0.36157161],
       [0.47785046, 0.58686408, 0.19883253, 0.46755602, 0.06427494],
       [0.64300614, 0.58682261, 0.56031068, 0.43677376, 0.39164197]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

**Hint: Use search about [dtype objects](https://numpy.org/doc/stable/reference/arrays.dtypes.html) and [bytes](https://numpy.org/devdocs/user/basics.types.html)**

In [ ]:
colors = np.dtype([
    ('r', np.ubyte),
    ('g', np.ubyte),
    ('b', np.ubyte),
    ('a', np.ubyte)
])
colors

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1 = np.random.randint(99, size=(5, 3))
matrix2 = np.random.randint(99, size=(3, 2))
print(f'Matrix 1:\n{matrix1}')
print()
print(f'Matrix 2:\n{matrix2}')

Matrix 1:
[[82 15  8]
 [14 77 74]
 [ 6 72 57]
 [20 37 96]
 [14 70 36]]

Matrix 2:
[[38 96]
 [53 11]
 [53 60]]


In [ ]:
np.dot(matrix1, matrix2)

array([[4335, 8517],
       [8535, 6631],
       [7065, 4788],
       [7809, 8087],
       [6150, 4274]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
rand_array = np.random.randint(10, size=(10))
rand_array

array([0, 2, 3, 9, 2, 7, 4, 5, 5, 7])

In [ ]:
mask = (rand_array <= 3) | (rand_array >= 8)
result = rand_array[mask]
result

array([0, 2, 3, 9, 2])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

**Answer:** It happens because the built-in `sum` and `np.sum` have different behaviors. The second sum, will consider the edges

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
import numpy as np

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Just the last operation is not legal

**Some material**:
1. [Bit shift operators](https://stackoverflow.com/questions/38491204/numpy-and-operators)

In [ ]:
Z = np.arange(10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Z**Z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [ ]:
print(2 << Z)
print(Z >> 2)
print(2 << Z >> 2)

[   2    4    8   16   32   64  128  256  512 1024]
[0 0 0 0 1 1 1 1 2 2]
[  0   1   2   4   8  16  32  64 128 256]


In [ ]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
Z >- Z

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
1j * Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [ ]:
Z / 1 / 1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
try:
  Z < Z > Z
except ValueError:
  print("ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(f'np.array(0) / np.array(0) = {np.array(0) / np.array(0)}')
print(f'np.array(0) // np.array(0) = {np.array(0) // np.array(0)}')
print(f'np.array([np.nan]).astype(int).astype(float) = {np.array([np.nan]).astype(int).astype(float)}')

np.array(0) / np.array(0) = nan
np.array(0) // np.array(0) = 0
np.array([np.nan]).astype(int).astype(float) = [-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

**Useful links:**
1. [np.copysign](https://numpy.org/doc/stable/reference/generated/numpy.copysign.html)
2. [np.uniform](https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html)
3. [np.round](https://numpy.org/doc/stable/reference/generated/numpy.around.html)
4. [np.ceil](https://numpy.org/doc/stable/reference/generated/numpy.ceil.html)
5. [np.floor](https://numpy.org/doc/stable/reference/generated/numpy.floor.html)
6. [np.abs](https://numpy.org/doc/stable/reference/generated/numpy.floor.html)

In [ ]:
float_arr = np.random.uniform(-10,+10,10)
float_arr

array([-3.83311305, -3.66031086,  5.28476769, -9.63848639,  2.98819598,
        7.34578894, -6.62816015, -8.59893253,  6.42229369,  5.86490499])

In [ ]:
round_arr = np.round(float_arr)
round_arr

array([ -4.,  -4.,   5., -10.,   3.,   7.,  -7.,  -9.,   6.,   6.])

In [ ]:
print(np.copysign(np.ceil(np.abs(float_arr)), float_arr))

[ -4.  -4.   6. -10.   3.   8.  -7.  -9.   7.   6.]


#### 30. How to find common values between two arrays? (★☆☆)

* Find the intersection values: [np.intersect1d](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

In [ ]:
arr1 = np.random.randint(0, 10, 10)
arr1

array([0, 7, 9, 3, 4, 4, 0, 6, 0, 7])

In [ ]:
arr2 = np.random.randint(0, 10, 10)
arr2

array([5, 3, 9, 4, 2, 2, 8, 5, 1, 1])

In [ ]:
intersection = np.intersect1d(arr1, arr2)
intersection

array([3, 4, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


### Warning!!!!!
Don't execute these lines, plsss

In [ ]:
# defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0

# Back to sanity
# _ = np.seterr(**defaults)

# Equivalently with a context manager
# with np.errstate(all="ignore"):
#     np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

### Remember
* The square root of a negative number will be an imaginary number
* The numpy square root method can't calculate this, because it doesn't support imaginary numbers
* The `emath.sqrt(x)` can do this!

### Numpy Mathematical Functions
[check this link!](https://numpy.org/doc/stable/reference/routines.emath.html)

In [ ]:
np.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.emath.sqrt(-1)

1j

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [ ]:
print(f'''today: {today}
yesterday: {yesterday}
tomorrow: {tomorrow}''')

today: 2022-09-27
yesterday: 2022-09-26
tomorrow: 2022-09-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

**Useful links:**
1. [How to apply functions to every element in a numpy array](https://thispointer.com/apply-a-function-to-every-element-in-numpy-array/)

In [ ]:
import calendar

weekdays = np.array(['Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu'])
k = -2

def convert_date_to_weekday(date):
  """ Convert a forma date YYYY-MM-DD to weekday"""
  global k
  k += 1
  return f'{weekdays[k % 7]} - ({date})'

weekday_function = np.vectorize(convert_date_to_weekday)
july_2016 = weekday_function(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))
july_2016

array(['Fri - (2016-07-01)', 'Sat - (2016-07-02)', 'Sun - (2016-07-03)',
       'Mon - (2016-07-04)', 'Tue - (2016-07-05)', 'Wed - (2016-07-06)',
       'Thu - (2016-07-07)', 'Fri - (2016-07-08)', 'Sat - (2016-07-09)',
       'Sun - (2016-07-10)', 'Mon - (2016-07-11)', 'Tue - (2016-07-12)',
       'Wed - (2016-07-13)', 'Thu - (2016-07-14)', 'Fri - (2016-07-15)',
       'Sat - (2016-07-16)', 'Sun - (2016-07-17)', 'Mon - (2016-07-18)',
       'Tue - (2016-07-19)', 'Wed - (2016-07-20)', 'Thu - (2016-07-21)',
       'Fri - (2016-07-22)', 'Sat - (2016-07-23)', 'Sun - (2016-07-24)',
       'Mon - (2016-07-25)', 'Tue - (2016-07-26)', 'Wed - (2016-07-27)',
       'Thu - (2016-07-28)', 'Fri - (2016-07-29)', 'Sat - (2016-07-30)',
       'Sun - (2016-07-31)'], dtype='<U18')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

**Answer:** Use the `out` argument

In [ ]:
A = np.random.randint(0, 10, 10).astype('float64')
A

array([3., 8., 7., 5., 5., 7., 4., 9., 6., 8.])

In [ ]:
B = np.random.randint(0, 10, 10).astype('float64')
B

array([7., 6., 1., 3., 2., 0., 7., 5., 7., 2.])

In [ ]:
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-15. , -56. , -28. , -20. , -17.5, -24.5, -22. , -63. , -39. ,
       -40. ])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.uniform(0, 10, 10)
arr

array([2.29748165, 2.98710463, 7.51539489, 4.94159099, 6.51937887,
       1.82309367, 7.96260062, 3.62273363, 9.16084788, 3.3520227 ])

In [ ]:
np.floor(arr).astype('int64')

array([2, 2, 7, 4, 6, 1, 7, 3, 9, 3])

In [ ]:
arr.astype('int64')

array([2, 2, 7, 4, 6, 1, 7, 3, 9, 3])

In [ ]:
arr // 1

array([2., 2., 7., 4., 6., 1., 7., 3., 9., 3.])

In [ ]:
arr - arr % 1

array([2., 2., 7., 4., 6., 1., 7., 3., 9., 3.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

**Answer:** Use [fromiter](https://numpy.org/doc/stable/reference/generated/numpy.fromiter.html)

In [ ]:
def generator_number():
  for i in range(10):
    yield i
result = np.fromiter(generator_number(), dtype='float')
result

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.random.rand(10)

array([0.97285051, 0.64603312, 0.52208173, 0.01884922, 0.33284621,
       0.43095001, 0.55062216, 0.56283756, 0.99830742, 0.47815325])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.array([1, 5, 45, 34, 0, 0, 13, 4, 24, 6, 10])
np.sort(arr)

array([ 0,  0,  1,  4,  5,  6, 10, 13, 24, 34, 45])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
small_arr = np.arange(10)
np.add.reduce(small_arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)
* `np.array_equal` test if two arrays has the same elements and same shape

In [ ]:
A = np.random.randint(0, 10, 10)
A

array([7, 8, 1, 7, 5, 5, 8, 9, 8, 3])

In [ ]:
B = np.random.randint(0, 10, 10)
B

array([1, 8, 7, 7, 9, 0, 8, 0, 6, 5])

In [ ]:
equal = np.array_equal(A, B)
equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
array = np.zeros(10)
array.flags.writeable = False
array[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

**Hint:** <a href="https://www.varsitytutors.com/hotmath/hotmath_help/topics/polar-coordinates#:~:text=To%20convert%20from%20Cartesian%20coordinates,1(yx))%20.">Cartesian coordinates $\to$ Polar coordinates</a>

In [ ]:
matrix = np.random.random((10, 2))
matrix

array([[0.86142229, 0.04410235],
       [0.47593485, 0.66903662],
       [0.59014135, 0.9855274 ],
       [0.59323503, 0.68256252],
       [0.24272294, 0.99613078],
       [0.04902181, 0.12698676],
       [0.22538933, 0.616382  ],
       [0.34315428, 0.9217848 ],
       [0.14184998, 0.31400837],
       [0.89092566, 0.80300507]])

In [ ]:
x, y = matrix[:, 0], matrix[:, 1]
r = np.sqrt((x ** 2) + (y ** 2))
t = np.arctan2(y, x)
t

array([0.05115247, 0.95247793, 1.03125401, 0.85530106, 1.33178816,
       1.20238316, 1.22023477, 1.21441985, 1.14649678, 0.7335414 ])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
rand_vec = np.random.random(10)
rand_vec

array([0.02319026, 0.08208831, 0.91548847, 0.34275265, 0.28067657,
       0.11598798, 0.77220663, 0.09157992, 0.25833155, 0.07690251])

In [ ]:
idx_max_val = rand_vec.argmax()
idx_max_val

2

In [ ]:
rand_vec[idx_max_val] = 0
rand_vec

array([0.02319026, 0.08208831, 0.        , 0.34275265, 0.28067657,
       0.11598798, 0.77220663, 0.09157992, 0.25833155, 0.07690251])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### What is a Cauchy matrix?

Let  $x_1$, $x_2$, ..., $x_m$ and $y_1$, $y_2$, ..., $y_n$ be elements in a field $F$, satisfying the that:
1. $x_1, ..., x_m$ are distincts
2. $y_1, ..., y_n$ are distincts and
3. $x_i+y_j \not= 0$ for $1 \leq i \leq m$, $1 \leq i \leq n$

$$
\begin{bmatrix}
   \dfrac{1}{x_1+y_1} & \dfrac{1}{x_2+y_2} &\dots&\dfrac{1}{x_1+y_n}\\
   \dfrac{1}{x_1+y_1} & \dfrac{1}{x_2+y_2} &\dots&\dfrac{1}{x_2+y_n}\\
   \vdots             & \vdots             &\ddots&\vdots\\
   \dfrac{1}{x_m+y_1} & \dfrac{1}{x_m+y_2} &\dots&\dfrac{1}{x_m+y_n}
\end{bmatrix}
$$

is called a *Cauchy matrix* over $F$

#### Useful links
1. [Cauchy matrix](http://planetmath.org/cauchymatrix)
2. [Determinant](https://mathworld.wolfram.com/Determinant.html)
3. [np.subtract docs](https://numpy.org/doc/stable/reference/generated/numpy.subtract.html)
4. [np.linalg docs](https://numpy.org/doc/stable/reference/routines.linalg.html)


In [ ]:
x = np.random.randint(1, 11, 4)
y = x + 0.4

In [ ]:
C = 1.0 / np.subtract.outer(x, y)
C

array([[-2.5       , -0.41666667, -0.22727273,  0.27777778],
       [ 0.625     , -2.5       , -0.41666667,  0.17857143],
       [ 0.27777778,  0.625     , -2.5       ,  0.13157895],
       [-0.22727273, -0.15625   , -0.11904762, -2.5       ]])

In [ ]:
np.linalg.det(C)

43.54805621147662

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
int_types = [np.int8, np.int32, np.int64]
for int_type in int_types:
  print(np.iinfo(int_type).min)
  print(np.iinfo(int_type).max)
  print("-----------------")

-128
127
-----------------
-2147483648
2147483647
-----------------
-9223372036854775808
9223372036854775807
-----------------


In [ ]:
float_types = [np.float32, np.float64]
for float_type in float_types:
  print(np.finfo(float_type).min)
  print(np.finfo(float_type).max)
  print(np.finfo(float_type).eps)
  print("-----------------")

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-----------------
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
-----------------


#### 49. How to print all the values of an array? (★★☆)

* [np.set_printoptions docs](https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html)

In [ ]:
np.set_printoptions(threshold=float('inf'))
arr = np.zeros((5, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
vec = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(vec - v)).argmin()
vec[index]

97

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
rand_vec = np.random.random((10, 2))
x, y = np.atleast_2d(rand_vec[:, 0], rand_vec[:, 1])

In [ ]:
x

array([[0.31253517, 0.01651943, 0.44278756, 0.71718558, 0.24745582,
        0.07132463, 0.68745083, 0.55615646, 0.78893565, 0.25010224]])

In [ ]:
y

array([[0.98898628, 0.858244  , 0.0990851 , 0.08802448, 0.7651367 ,
        0.92273329, 0.55083108, 0.47660131, 0.64187344, 0.72116032]])

In [ ]:
d = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)
d

array([[0.        , 0.32360293, 0.89938301, 0.98766093, 0.2331179 ,
        0.25014393, 0.57666432, 0.56735324, 0.58944443, 0.27500658],
       [0.32360293, 0.        , 0.87064732, 1.0412354 , 0.24899917,
        0.08463142, 0.73800518, 0.6609533 , 0.802149  , 0.27083734],
       [0.89938301, 0.87064732, 0.        , 0.27462084, 0.69410318,
        0.90353807, 0.51374561, 0.39417127, 0.64376834, 0.6512336 ],
       [0.98766093, 1.0412354 , 0.27462084, 0.        , 0.82409162,
        1.05540285, 0.46376083, 0.42062136, 0.55847717, 0.78678322],
       [0.2331179 , 0.24899917, 0.69410318, 0.82409162, 0.        ,
        0.23634484, 0.48941037, 0.4225503 , 0.55533254, 0.04405594],
       [0.25014393, 0.08463142, 0.90353807, 1.05540285, 0.23634484,
        0.        , 0.7196685 , 0.65885936, 0.77061523, 0.26943106],
       [0.57666432, 0.73800518, 0.51374561, 0.46376083, 0.48941037,
        0.7196685 , 0.        , 0.1508253 , 0.13633737, 0.46934619],
       [0.56735324, 0.6609533 , 0.3941712

* Using `scipy`

In [ ]:
import scipy
import scipy.spatial
Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z, Z)
D

array([[0.        , 0.15256321, 0.51408175, 0.30311338, 0.14028992,
        0.13971804, 0.41154413, 0.58963404, 0.18522988, 0.49080276],
       [0.15256321, 0.        , 0.38099751, 0.31564341, 0.01903879,
        0.28019769, 0.55332541, 0.71189447, 0.07743439, 0.35614853],
       [0.51408175, 0.38099751, 0.        , 0.66146255, 0.38426164,
        0.60012233, 0.83967856, 0.92779306, 0.32887297, 0.02585545],
       [0.30311338, 0.31564341, 0.66146255, 0.        , 0.32509487,
        0.41098015, 0.63578633, 0.84609419, 0.39268018, 0.63561199],
       [0.14028992, 0.01903879, 0.38426164, 0.32509487, 0.        ,
        0.26410932, 0.53667618, 0.69345141, 0.06839329, 0.35980571],
       [0.13971804, 0.28019769, 0.60012233, 0.41098015, 0.26410932,
        0.        , 0.2737735 , 0.45163684, 0.28612357, 0.57955223],
       [0.41154413, 0.55332541, 0.83967856, 0.63578633, 0.53667618,
        0.2737735 , 0.        , 0.22302152, 0.55034185, 0.82234648],
       [0.58963404, 0.71189447, 0.9277930

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
arr_32 = (np.random.rand(10) * 100).astype(np.float32)
copy_arr = arr_32.view(np.int32)
copy_arr[:] = arr_32
copy_arr

array([82, 32, 23, 20, 35, 82, 71, 26, 59, 91], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

* [IO library](https://docs.python.org/3/library/io.html)
* [np.genfromtxt docs](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html)

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')

Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
Z

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int32)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
  print(f'Index={index}\tValue={value}')

Index=(0, 0)	Value=0
Index=(0, 1)	Value=1
Index=(0, 2)	Value=2
Index=(1, 0)	Value=3
Index=(1, 1)	Value=4
Index=(1, 2)	Value=5
Index=(2, 0)	Value=6
Index=(2, 1)	Value=7
Index=(2, 2)	Value=8


In [ ]:
for index in np.ndindex(arr.shape):
  print(f'Index={index}\tValue={arr[index]}')

Index=(0, 0)	Value=0
Index=(0, 1)	Value=1
Index=(0, 2)	Value=2
Index=(1, 0)	Value=3
Index=(1, 1)	Value=4
Index=(1, 2)	Value=5
Index=(2, 0)	Value=6
Index=(2, 1)	Value=7
Index=(2, 2)	Value=8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x * x + y * y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 5
p = 3
arr = np.zeros((n, n))
np.put(arr, np.random.choice(range(n * n), p, replace=False), 55)
arr

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0., 55.,  0.,  0.,  0.],
       [ 0., 55.,  0.,  0.,  0.],
       [ 0.,  0., 55.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix = np.random.rand(5, 10)
y = matrix - matrix.mean(axis=1, keepdims=True)
y

array([[-0.20032669, -0.02393602,  0.35358507,  0.24549156, -0.28449888,
        -0.16813545,  0.06653681, -0.3035046 ,  0.42712047, -0.11233226],
       [-0.15568257,  0.4516941 , -0.10500899,  0.25696248, -0.06814533,
         0.14376227, -0.38739405, -0.39969161,  0.41696038, -0.15345668],
       [ 0.26976937, -0.00069703,  0.19409287,  0.02360339,  0.09107017,
        -0.43092748,  0.32792823,  0.23410978, -0.45232878, -0.25662052],
       [ 0.05431694,  0.13711806,  0.02645734,  0.06029111, -0.51120858,
         0.44391757, -0.22559458, -0.18139098,  0.35573419, -0.15964106],
       [ 0.38051233,  0.32305499, -0.27058501, -0.4774295 ,  0.3493237 ,
        -0.05164081, -0.22116317, -0.45183256,  0.28568688,  0.13407314]])

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
arr = np.random.randint(0, 100, (3,3))
arr

array([[27, 21, 62],
       [59, 39, 55],
       [ 8,  8, 78]])

In [ ]:
arr[arr[:, 0].argsort()]

array([[ 8,  8, 78],
       [27, 21, 62],
       [59, 39, 55]])

In [ ]:
arr[arr[:, 1].argsort()]

array([[ 8,  8, 78],
       [27, 21, 62],
       [59, 39, 55]])

In [ ]:
arr[arr[:, 2].argsort()]

array([[59, 39, 55],
       [27, 21, 62],
       [ 8,  8, 78]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0, 5, (3, 10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
arr = np.random.uniform(0, 1, 10)
k = 0.5

In [ ]:
arr

array([0.92592759, 0.78359354, 0.53989432, 0.12576788, 0.70967207,
       0.79466498, 0.75690659, 0.21337136, 0.88837102, 0.90634703])

In [ ]:
m = arr.flat[np.abs(arr - k).argmin()]
m

0.5398943195303975

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)

In [ ]:
it = np.nditer([A, B, None])
it

In [ ]:
for x, y, z in it:
  z[...] = x + y
it.operands[2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):

  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj

  def __array_finalize__(self, obj):
    if obj is None: return
    self.info = getattr(obj, 'name', 'no name')

In [ ]:
arr = NamedArray(np.arange(10), "range_10")
arr.name

'range_10'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength=len(Z))
Z

array([2., 3., 2., 4., 1., 6., 5., 4., 2., 1.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = list(range(1, 7))
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)

In [ ]:
I

array([[[0, 0, 0],
        [1, 1, 0],
        [3, 0, 3],
        ...,
        [0, 3, 1],
        [2, 1, 1],
        [0, 1, 3]],

       [[0, 2, 0],
        [1, 1, 3],
        [3, 3, 2],
        ...,
        [1, 2, 0],
        [2, 0, 3],
        [0, 1, 2]],

       [[0, 2, 0],
        [2, 3, 2],
        [3, 1, 1],
        ...,
        [0, 1, 2],
        [2, 1, 1],
        [1, 1, 3]],

       ...,

       [[1, 3, 2],
        [1, 1, 1],
        [0, 2, 3],
        ...,
        [3, 3, 0],
        [3, 0, 0],
        [3, 0, 0]],

       [[0, 2, 3],
        [2, 2, 1],
        [1, 1, 2],
        ...,
        [0, 2, 3],
        [1, 1, 1],
        [3, 2, 2]],

       [[1, 0, 3],
        [3, 3, 0],
        [1, 1, 0],
        ...,
        [2, 3, 1],
        [2, 1, 1],
        [2, 0, 1]]], dtype=uint8)

In [ ]:
colors

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 3],
       [0, 1, 0],
       [0, 1, 1],
       [0, 1, 2],
       [0, 1, 3],
       [0, 2, 0],
       [0, 2, 1],
       [0, 2, 2],
       [0, 2, 3],
       [0, 3, 0],
       [0, 3, 1],
       [0, 3, 2],
       [0, 3, 3],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 2],
       [1, 0, 3],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 3],
       [1, 2, 0],
       [1, 2, 1],
       [1, 2, 2],
       [1, 2, 3],
       [1, 3, 0],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 3],
       [2, 0, 0],
       [2, 0, 1],
       [2, 0, 2],
       [2, 0, 3],
       [2, 1, 0],
       [2, 1, 1],
       [2, 1, 2],
       [2, 1, 3],
       [2, 2, 0],
       [2, 2, 1],
       [2, 2, 2],
       [2, 2, 3],
       [2, 3, 0],
       [2, 3, 1],
       [2, 3, 2],
       [2, 3, 3],
       [3, 0, 0],
       [3, 0, 1],
       [3, 0, 2],
       [3, 0, 3],
       [3, 1, 0],
       [3, 1, 1],
       [3, 1, 2],
       [3,

In [ ]:
len(colors)

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
s = A.sum(axis=(-2, -1))
s

array([[50, 66, 32, 49],
       [53, 57, 47, 46],
       [59, 39, 56, 48]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)

In [ ]:
D_sums

array([4.85797365, 5.85975304, 1.73668888, 4.77676314, 5.5122946 ,
       6.28008067, 3.42013061, 5.26753888, 7.72324858, 3.71485881])

In [ ]:
D_counts = np.bincount(S)

In [ ]:
D_counts

array([11, 10,  5,  8, 13, 11,  9, 10, 15,  8])

In [ ]:
D_means = D_sums / D_counts
D_means

array([0.44163397, 0.5859753 , 0.34733778, 0.59709539, 0.42402266,
       0.57091642, 0.38001451, 0.52675389, 0.51488324, 0.46435735])

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))

In [ ]:
np.sum(A * B.T, axis=1)

array([0.5219871 , 1.82109099, 0.92521187, 1.11239068, 1.28156439])

In [ ]:
np.einsum("ij, ji->i", A, B)

array([0.5219871 , 1.82109099, 0.92521187, 1.11239068, 1.28156439])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array(list(range(1, 6)))
nz = 3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * (nz))

In [ ]:
Z0[::nz + 1] = Z
Z0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
A * B[:, :, None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
G

array([( 2, 25), ( 2, 35), ( 2, 52), ( 2, 72), ( 4, 10), ( 4, 62),
       ( 5, 17), ( 5, 61), (10, 62), (16, 17), (16, 40), (16, 94),
       (16, 98), (17, 61), (17, 98), (23, 39), (23, 92), (25, 72),
       (33, 75), (33, 87), (35, 52), (38, 83), (38, 91), (39, 92),
       (40, 94), (75, 87), (83, 91), (87, 90), (87, 98), (90, 98)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
arr = np.bincount([1, 1, 2, 3, 4, 4, 6])
a = np.repeat(np.arange(len(arr)), arr)
a

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3):
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n

In [ ]:
arr = np.arange(20)
moving_average(arr, 3)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.strides[0], a.strides[0])
  return stride_tricks.as_strided(a, shape=shape, strides=strides)

In [ ]:
Z = rolling(np.arange(10), 3)
Z

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.82721761, -0.98392928,  0.60938463, -0.44240207,  0.79821474,
        0.4982981 , -0.70383246, -0.42274805, -0.89819837, -0.15209958,
        0.98421815, -0.17961526,  0.40639334, -0.23348676,  0.67418928,
       -0.72111329,  0.10771102,  0.96200806,  0.65192348, -0.3169166 ,
       -0.5990237 , -0.33260942, -0.29358243, -0.01580816,  0.94196647,
       -0.60471858,  0.58603222, -0.88141267,  0.17395041, -0.73835009,
        0.68630432, -0.72603166,  0.86516259,  0.53647357, -0.08676496,
       -0.89585484,  0.3093073 ,  0.08088174, -0.6560397 , -0.9452602 ,
       -0.56752632, -0.94224063, -0.25614883, -0.31503627,  0.53882198,
       -0.60757933,  0.46012443,  0.29744285, -0.75209831, -0.55824047,
       -0.21853208,  0.99652175,  0.96756333, -0.30357215,  0.83091575,
        0.30078729, -0.21485187, -0.20451103, -0.58378   , -0.60958271,
        0.21070976,  0.57512531,  0.34700492, -0.31591647,  0.87385717,
       -0.0356031 , -0.28382166, -0.51772192,  0.49200891,  0.15

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
  T = P1 - P0
  L = (T ** 2).sum(axis=1)
  U = -((P0[:, 0] - p[..., 0]) * T[:, 0] + (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
  U = U.reshape(len(U), 1)
  D = P0 + U * T - p
  return np.sqrt((D ** 2).sum(axis=1))

In [ ]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))

In [ ]:
distance(P0, P1, p)

array([3.00978925, 6.07811412, 0.55593167, 5.03348542, 8.1655467 ,
       4.42821544, 3.31155059, 5.6739805 , 8.35135091, 4.74542669])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
np.array([distance(P0,P1,p_i) for p_i in p])

array([[ 8.04456288, 11.21466023,  5.75307446,  2.06727347,  3.52394562,
         0.954132  ,  1.73651637,  2.07314328,  5.62987495,  1.45286252],
       [13.73064748,  9.88044448,  3.28577384,  1.11952478,  0.33726513,
         6.66221834,  7.29026083,  2.42367982, 10.85393427,  4.27273432],
       [ 9.19878466, 12.44254609,  6.68720675,  3.3802587 ,  4.23140459,
         2.06457067,  3.04244332,  3.62119162,  5.88671618,  0.59635765],
       [ 4.20756132,  3.96605947,  0.38429946,  5.47827619,  1.6894931 ,
         2.63537231,  2.98210867,  6.1936616 ,  6.47400498,  3.65415044],
       [ 6.38050585,  4.85697281,  9.28674149, 14.19050706, 10.41951659,
         0.18638872,  1.85023225, 14.25179588, 12.92779455,  0.22977181],
       [ 4.455254  , 14.72011007,  9.86049715,  5.34058556,  7.94216441,
         2.73480459,  1.4519353 ,  4.47631704,  0.90422558,  5.61041083],
       [11.98386102,  2.60833737,  3.31149236,  6.30539324,  5.62563797,
         5.15598404,  4.66883889,  5.25411382

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

In [ ]:
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

In [ ]:
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

In [ ]:
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

In [ ]:
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
print(Z, '\n\n', R)

[[1 4 9 1 8 7 8 0 9 5]
 [2 0 6 2 2 9 9 2 4 7]
 [8 3 3 4 7 1 1 7 6 4]
 [5 9 8 5 5 7 1 2 1 3]
 [2 0 9 4 2 3 2 3 5 7]
 [7 8 0 9 4 0 7 6 8 3]
 [4 8 7 9 3 3 9 2 7 4]
 [9 6 2 6 3 4 7 6 4 1]
 [3 9 3 6 7 1 8 9 6 7]
 [0 9 4 8 1 7 0 7 2 1]] 

 [[0 0 0 0 0]
 [0 1 4 9 1]
 [0 2 0 6 2]
 [0 8 3 3 4]
 [0 5 9 8 5]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [6]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [7]:
matrix = np.random.uniform(0, 1, (5, 5))
U, S, V = np.linalg.svd(matrix)
rank = np.sum(S > 1e-10)
rank

5

#### 83. How to find the most frequent value in an array?

In [10]:
arr = np.random.randint(0, 10, 50)
arr

array([0, 4, 3, 2, 4, 6, 2, 5, 1, 7, 7, 4, 2, 3, 4, 6, 9, 3, 8, 6, 3, 3,
       8, 2, 5, 7, 8, 1, 5, 7, 7, 9, 5, 5, 7, 5, 9, 2, 6, 2, 0, 3, 5, 8,
       6, 6, 4, 6, 0, 0])

In [11]:
np.bincount(arr).argmax()

5

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [12]:
matrix = np.random.randint(0, 5, (10, 10))

In [13]:
n = 3
i = 1 + (matrix.shape[0] - 3)
j = 1 + (matrix.shape[1] - 3)

In [14]:
C = stride_tricks.as_strided(matrix, shape=(i, j, n, n), strides=matrix.strides + matrix.strides)
C

array([[[[4, 1, 0],
         [2, 2, 3],
         [3, 4, 0]],

        [[1, 0, 0],
         [2, 3, 2],
         [4, 0, 3]],

        [[0, 0, 0],
         [3, 2, 4],
         [0, 3, 2]],

        [[0, 0, 0],
         [2, 4, 1],
         [3, 2, 2]],

        [[0, 0, 2],
         [4, 1, 1],
         [2, 2, 1]],

        [[0, 2, 3],
         [1, 1, 0],
         [2, 1, 1]],

        [[2, 3, 0],
         [1, 0, 2],
         [1, 1, 0]],

        [[3, 0, 4],
         [0, 2, 2],
         [1, 0, 1]]],


       [[[2, 2, 3],
         [3, 4, 0],
         [2, 1, 0]],

        [[2, 3, 2],
         [4, 0, 3],
         [1, 0, 1]],

        [[3, 2, 4],
         [0, 3, 2],
         [0, 1, 4]],

        [[2, 4, 1],
         [3, 2, 2],
         [1, 4, 3]],

        [[4, 1, 1],
         [2, 2, 1],
         [4, 3, 4]],

        [[1, 1, 0],
         [2, 1, 1],
         [3, 4, 4]],

        [[1, 0, 2],
         [1, 1, 0],
         [4, 4, 0]],

        [[0, 2, 2],
         [1, 0, 1],
         [4, 0, 2]]],


    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [15]:
class Symetric(np.ndarray):
  def __setitem__(self, index, value):
    i, j = index
    super(Symetric, self).__setitem__((i, j), value)
    super(Symetric, self).__setitem__((j, i), value)

In [16]:
def symetric(Z):
  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

In [17]:
S = symetric(np.random.randint(0, 10, (5, 5)))
S

Symetric([[ 1,  3,  9,  9, 12],
          [ 3,  0,  3,  1, 12],
          [ 9,  3,  4, 10,  7],
          [ 9,  1, 10,  1,  6],
          [12, 12,  7,  6,  8]])

In [18]:
S[2, 3] = 42
S

Symetric([[ 1,  3,  9,  9, 12],
          [ 3,  0,  3,  1, 12],
          [ 9,  3,  4, 42,  7],
          [ 9,  1, 42,  1,  6],
          [12, 12,  7,  6,  8]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

It works, because:
  - M is (p,n,n)
  - V is (p,n,1)
  - Thus, summing over the paired axes 0 and 0 (of M and V independently) and 2 and 1, to remain with a (n,1) vector.

In [19]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))

In [20]:
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [21]:
Z = np.ones((16, 16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)

In [22]:
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [23]:
def iterate(Z):
  N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
       Z[1:-1, 0:-2]                 + Z[1:-1, 2:] +
       Z[2:  , 0:-2] + Z[2:  , 1:-1] + Z[2:  , 2:])
  
  birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
  survive = ((N == 2) | (N == 3)) * (Z[1:-1, 1:-1] == 1)
  Z[...] = 0
  Z[1:-1, 1:-1][birth | survive] = 1
  return Z

In [24]:
Z = np.random.randint(0, 2, (50, 50))
Z

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 0, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 1, 1]])

In [25]:
for i in range(100):
  Z = iterate(Z)

In [26]:
Z

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### 89. How to get the n largest values of an array (★★★)

In [27]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [28]:
Z[np.argpartition(-Z, n)[:n]]

array([9997, 9999, 9998, 9996, 9995])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [29]:
def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)
  
  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T

  for n, arr, in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]

  return ix

In [30]:
cartesian(([1, 2, 3], [4, 5], [6, 7]))

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

#### 91. How to create a record array from a regular array? (★★★)

In [31]:
Z = np.array([
    ("Hello", 2.5, 3),
    ("World", 3.6, 2)
])

In [32]:
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats='S8, f8, i8')

In [33]:
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [34]:
x = np.random.rand(int(5e7))

In [35]:
%timeit np.power(x, 3)
%timeit x * x * x
%timeit np.einsum('i,i,i->i', x, x, x)

3.45 s ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
197 ms ± 3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
155 ms ± 2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [36]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

In [37]:
C = (A[..., np.newaxis, np.newaxis] == B)
C

array([[[[False, False],
         [ True, False]],

        [[False, False],
         [False, False]],

        [[False, False],
         [False, False]]],


       [[[False, False],
         [False,  True]],

        [[False, False],
         [ True, False]],

        [[False, False],
         [False, False]]],


       [[[False, False],
         [False,  True]],

        [[False, False],
         [False, False]],

        [[False, False],
         [ True, False]]],


       [[[False, False],
         [False, False]],

        [[False, False],
         [False, False]],

        [[False, False],
         [False, False]]],


       [[[ True,  True],
         [False, False]],

        [[False, False],
         [ True, False]],

        [[ True,  True],
         [False, False]]],


       [[[False, False],
         [False, False]],

        [[ True,  True],
         [False, False]],

        [[False, False],
         [False, False]]],


       [[[False, False],
         [ True, False]],



In [41]:
rows = np.where(C.any((3,1)).all(1))[0]
rows

array([1, 2, 3, 5, 7])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [42]:
Z = np.random.randint(0, 5, (10, 3))
Z

array([[2, 1, 1],
       [4, 4, 0],
       [0, 1, 3],
       [0, 2, 0],
       [1, 1, 2],
       [4, 4, 3],
       [1, 1, 0],
       [3, 0, 0],
       [3, 2, 3],
       [3, 4, 0]])

In [43]:
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
U

array([[2, 1, 1],
       [4, 4, 0],
       [0, 1, 3],
       [0, 2, 0],
       [1, 1, 2],
       [4, 4, 3],
       [1, 1, 0],
       [3, 0, 0],
       [3, 2, 3],
       [3, 4, 0]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [44]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2 ** np.arange(8))) != 0).astype(int)
B[:, ::-1]

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [47]:
Z = np.random.randint(0,2,(6,3))
np.unique(Z, axis=0)

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [48]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

In [49]:
np.einsum('i->', A)

5.647078654709999

In [50]:
np.einsum('i,i->i', A, B)

array([0.06609352, 0.78932581, 0.00669521, 0.70853404, 0.07157981,
       0.38519347, 0.17764127, 0.07973218, 0.84591577, 0.21863714])

In [51]:
np.einsum('i,i', A, B)

3.3493482470011866

In [52]:
np.einsum('i,j->ij', A, B)

array([[6.60935248e-02, 1.92077936e-01, 2.09563268e-01, 1.64360854e-01,
        9.58291772e-02, 9.33437516e-02, 1.11453370e-01, 2.19951400e-02,
        2.07307421e-01, 1.73022016e-01],
       [2.71604985e-01, 7.89325811e-01, 8.61180101e-01, 6.75425128e-01,
        3.93800790e-01, 3.83587172e-01, 4.58006907e-01, 9.03869130e-02,
        8.51909915e-01, 7.11017339e-01],
       [2.11158216e-03, 6.13658215e-03, 6.69521047e-03, 5.25106582e-03,
        3.06158859e-03, 2.98218323e-03, 3.56075650e-03, 7.02709463e-04,
        6.62313978e-03, 5.52777604e-03],
       [2.84918891e-01, 8.28018066e-01, 9.03394609e-01, 7.08534044e-01,
        4.13104657e-01, 4.02390375e-01, 4.80458119e-01, 9.48176227e-02,
        8.93670004e-01, 7.45870962e-01],
       [4.93687038e-02, 1.43473037e-01, 1.56533744e-01, 1.22769702e-01,
        7.15798148e-02, 6.97233207e-02, 8.32503400e-02, 1.64293182e-02,
        1.54848734e-01, 1.29239176e-01],
       [2.72742352e-01, 7.92631173e-01, 8.64786358e-01, 6.78253522e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [53]:
phi = np.arange(0, 10 * np.pi, 0.1)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)

In [54]:
dr = (np.diff(x) ** 2 + np.diff(y) ** 2) **.5
dr

array([0.1       , 0.10099422, 0.10295387, 0.10582533, 0.10953691,
       0.11400658, 0.11914907, 0.12488128, 0.1311259 , 0.13781329,
       0.14488215, 0.15227936, 0.15995938, 0.16788341, 0.17601848,
       0.18433667, 0.19281427, 0.20143115, 0.21017019, 0.21901677,
       0.22795836, 0.2369842 , 0.24608504, 0.25525285, 0.26448065,
       0.2737624 , 0.28309278, 0.29246713, 0.30188136, 0.31133186,
       0.32081541, 0.33032917, 0.33987061, 0.34943745, 0.35902767,
       0.36863944, 0.37827112, 0.38792122, 0.39758841, 0.40727146,
       0.41696928, 0.42668085, 0.43640526, 0.44614167, 0.4558893 ,
       0.46564746, 0.4754155 , 0.48519281, 0.49497885, 0.50477312,
       0.51457514, 0.52438447, 0.53420072, 0.54402351, 0.55385249,
       0.56368734, 0.57352776, 0.58337346, 0.59322418, 0.60307968,
       0.61293972, 0.62280409, 0.63267259, 0.64254503, 0.65242122,
       0.662301  , 0.67218422, 0.68207071, 0.69196035, 0.701853  ,
       0.71174853, 0.72164683, 0.73154777, 0.74145127, 0.75135

In [55]:
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r

array([0.00000000e+00, 1.00000000e-01, 2.00994225e-01, 3.03948099e-01,
       4.09773428e-01, 5.19310334e-01, 6.33316917e-01, 7.52465988e-01,
       8.77347271e-01, 1.00847317e+00, 1.14628646e+00, 1.29116861e+00,
       1.44344797e+00, 1.60340735e+00, 1.77129076e+00, 1.94730924e+00,
       2.13164591e+00, 2.32446017e+00, 2.52589132e+00, 2.73606151e+00,
       2.95507828e+00, 3.18303664e+00, 3.42002084e+00, 3.66610588e+00,
       3.92135873e+00, 4.18583938e+00, 4.45960178e+00, 4.74269456e+00,
       5.03516168e+00, 5.33704304e+00, 5.64837490e+00, 5.96919031e+00,
       6.29951948e+00, 6.63939009e+00, 6.98882753e+00, 7.34785520e+00,
       7.71649464e+00, 8.09476576e+00, 8.48268698e+00, 8.88027538e+00,
       9.28754684e+00, 9.70451612e+00, 1.01311970e+01, 1.05676022e+01,
       1.10137439e+01, 1.14696332e+01, 1.19352807e+01, 1.24106962e+01,
       1.28958890e+01, 1.33908678e+01, 1.38956409e+01, 1.44102161e+01,
       1.49346005e+01, 1.54688013e+01, 1.60128248e+01, 1.65666773e+01,
      

In [56]:
r_int = np.linspace(0, r.max(), 200)
r_int

array([  0.        ,   2.48788858,   4.97577716,   7.46366574,
         9.95155432,  12.43944289,  14.92733147,  17.41522005,
        19.90310863,  22.39099721,  24.87888579,  27.36677437,
        29.85466295,  32.34255152,  34.8304401 ,  37.31832868,
        39.80621726,  42.29410584,  44.78199442,  47.269883  ,
        49.75777158,  52.24566016,  54.73354873,  57.22143731,
        59.70932589,  62.19721447,  64.68510305,  67.17299163,
        69.66088021,  72.14876879,  74.63665736,  77.12454594,
        79.61243452,  82.1003231 ,  84.58821168,  87.07610026,
        89.56398884,  92.05187742,  94.539766  ,  97.02765457,
        99.51554315, 102.00343173, 104.49132031, 106.97920889,
       109.46709747, 111.95498605, 114.44287463, 116.9307632 ,
       119.41865178, 121.90654036, 124.39442894, 126.88231752,
       129.3702061 , 131.85809468, 134.34598326, 136.83387184,
       139.32176041, 141.80964899, 144.29753757, 146.78542615,
       149.27331473, 151.76120331, 154.24909189, 156.73

In [57]:
x_int = np.interp(r_int, r, x)
x_int

array([ 0.00000000e+00, -3.73131229e-01, -2.59817608e+00, -3.26212050e+00,
       -2.18442687e+00, -2.98929946e-02,  2.42923642e+00,  4.54913599e+00,
        5.92318348e+00,  6.35117933e+00,  5.82369277e+00,  4.46259540e+00,
        2.47320794e+00,  1.09577220e-01, -2.36575300e+00, -4.71261671e+00,
       -6.72701769e+00, -8.25541575e+00, -9.18486120e+00, -9.46381505e+00,
       -9.11085788e+00, -8.12875279e+00, -6.63306046e+00, -4.69271059e+00,
       -2.44736165e+00, -2.05444585e-02,  2.46101146e+00,  4.86841760e+00,
        7.08937968e+00,  9.02539126e+00,  1.05948609e+01,  1.17357250e+01,
        1.24068974e+01,  1.25885805e+01,  1.22815267e+01,  1.15053927e+01,
        1.02963689e+01,  8.70429550e+00,  6.78948686e+00,  4.61716636e+00,
        2.25853448e+00, -1.98731680e-01, -2.68040566e+00, -5.11543300e+00,
       -7.41973991e+00, -9.53891040e+00, -1.14237629e+01, -1.29919305e+01,
       -1.42355069e+01, -1.51243232e+01, -1.56061571e+01, -1.57219415e+01,
       -1.54217066e+01, -

In [59]:
y_int = np.interp(r_int, r, y)
y_int

array([ 0.00000000e+00,  1.74026724e+00,  9.81816584e-01, -1.34251287e+00,
       -3.53191891e+00, -4.70449474e+00, -4.59573427e+00, -3.33831870e+00,
       -1.28956083e+00,  1.14234685e+00,  3.55645601e+00,  5.62188218e+00,
        7.09389488e+00,  7.82951803e+00,  7.78700678e+00,  6.99685666e+00,
        5.55535240e+00,  3.60417006e+00,  1.30506373e+00, -1.15819722e+00,
       -3.61328132e+00, -5.89130465e+00, -7.87065053e+00, -9.41689057e+00,
       -1.04714836e+01, -1.09903787e+01, -1.09354306e+01, -1.03330912e+01,
       -9.22690166e+00, -7.67489830e+00, -5.75257980e+00, -3.54832201e+00,
       -1.15854355e+00,  1.31709956e+00,  3.78023622e+00,  6.13780326e+00,
        8.30540149e+00,  1.02098724e+01,  1.17910419e+01,  1.29972950e+01,
        1.37774249e+01,  1.41319792e+01,  1.40585758e+01,  1.35636816e+01,
        1.26345244e+01,  1.13409083e+01,  9.72216360e+00,  7.79464305e+00,
        5.64544223e+00,  3.32503222e+00,  8.88107041e-01, -1.59329248e+00,
       -4.05992507e+00, -

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [62]:
X = np.asarray([
    [1, 0, 3, 8],
    [2, 0, 1, 1],
    [1.5, 2.5, 1, 0]
], dtype='float32')
X

array([[1. , 0. , 3. , 8. ],
       [2. , 0. , 1. , 1. ],
       [1.5, 2.5, 1. , 0. ]], dtype=float32)

In [63]:
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
M

array([False,  True, False])

In [64]:
X[M]

array([[2., 0., 1., 1.]], dtype=float32)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [74]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
confint

array([0.00345793, 0.39063449])